openapi: 3.0.3
info:
  title: Flooding application
  description: An API to show river levels and rainfall for Learn by Doing
  version: 0.0.1
servers:
  - url: 'http://localhost:9001'
paths:
  /river:
    get:
      summary: Get river level readings sorted in chronological order
      parameters: 
        - in: query
          name: start
          required: false
          schema:
            $ref: '#/components/schemas/Date'
          description: Start date of data to get
        - in: query
          name: page
          required: false
          schema:
            type: integer
            default: 1
          description: Page number of data to get
        - in: query
          name: pagesize
          required: false
          schema:
            type: integer
            default: 12
          description: Number of measurements per page of data
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  readings:
                    type: array
                    items:
                      $ref: '#/components/schemas/RiverReading'
  /rainfall/{station}:
    get:
      summary: Get rainfall readings for a measuring station sorted in chronological order
      parameters: 
        - in: query
          name: start
          required: false
          schema:
            $ref: '#/components/schemas/Date'
          description: Start date of data to get
        - in: query
          name: page
          required: false
          schema:
            type: integer
            default: 1
          description: Page number of data to get
        - in: query
          name: pagesize
          required: false
          schema:
            type: integer
            default: 12
          description: Number of measurements per page of data
        - in: path
          name: station
          required: true
          schema:
            $ref: '#/components/schemas/Station'
          description: Name of the station to get data for
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  readings:
                    type: array
                    items:
                      $ref: '#/components/schemas/RainfallReading'
components:
  schemas:
    Level:
      type: number
      minimum: 0
      example: 3.15
    Timestamp:
      type: string
      pattern: "^2[0-9]{3}-(0[0-9]|1[0-2])-([0-2][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$"
      example: "2025-01-20T09:15:00"
    Station:
      type: string
      enum:
        - acomb-codlaw-hill
        - allenheads-allen-lodge
        - alston
        - catcleugh
        - chirdon
        - garrigill-noonstones-hill
        - haltwhistle
        - hartside
        - hexham-firtrees
        - kielder-ridge-end
        - knarsdale
      example: catcleugh
    Date:
      type: string
      pattern: "^2[0-9]{3}-(0[0-9]|1[0-2])-([0-2][0-9]|3[01])$"
      example: "2022-12-25"
    RiverReading:
      type: object
      required:
        - timestamp
        - level
      properties:
        timestamp:
          $ref: '#/components/schemas/Timestamp'
        level:
          $ref: '#/components/schemas/Level'
    RainfallReading:
      type: object
      required:
        - timestamp
        - level
        - station
      properties:
        timestamp:
          $ref: '#/components/schemas/Timestamp'
        station:
          $ref: '#/components/schemas/Station'
        level:
          $ref: '#/components/schemas/Level'
